### ISSUE TITLE
BibTeX style for Geophysics does not include issue numbers for journal articles

### ISSUE THREAD

**Issue by erlendviggen** [SEGTeX/texmf#2]
When using the ``seg`` bibliographystyle with the ``geophysics`` document class, filling out the ``number`` field for ``article`` entries in the .bib file does not result in these issue numbers being included in the .blg file. Thus, there is currently no way to include journal issue numbers in SEGTeX-formatted Geophysics articles.

Thanks for the document class, by the way. I appreciate it, and it has otherwise served me well so far.

**Comment by sfomel** [comment]
Please try using issue= instead of number=

**Comment by erlendviggen** [comment]
It's a bit non-standard, but it works perfectly. Thanks!
