### ISSUE TITLE
Track change of SEG latex template

### ISSUE THREAD

**Issue by lixuekai2001** [SEGTeX/texmf#8]
The editor of GEOPHYSICS asked to make a track change. However, the SEG latext does not have the changes package to allow the user to track change. Or if there is another way to show the changes? It is appreciated if you can provide a solution on this.

**Comment by sfomel** [comment]
You can see an example of using \old{} and \new{} here: https://reproducibility.org/wikilocal/docs/geophysics_example.pdf
